eureka:
  client:

    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

mybatis:
  type-aliases-package: com.lqa.entity
  mapper-locations: classpath*:mapper/*Mapper.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lc?useSSL=false
    username: root
    password: root
